FROM python:3.9
EXPOSE 8080                     #this is for health check
WORKDIR /app
COPY payment.ini .
COPY *.py .
COPY requirements.txt .
RUN pip3 install -r requirements.txt
CMD ["uwsgi", "--ini", "payment.ini"]

