services:
  catalogue:
    build: ./catalogue
    image: dockerlearn255/catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb

  user:
    build: ./user
    image: dockerlearn255/user:1.0.0
    container_name: user
    depends_on:
      - redis
      - mongodb

  cart:
    build: ./cart
    image: dockerlearn255/cart:1.0.0
    container_name: cart
    depends_on:
      - redis   
      - catalogue 

  Shipping:
    build: ./shipping
    image: dockerlearn255/shipping:1.0.0
    container_name: shipping
    depends_on:
      - mysql 
      - cart   

  frontend:
    build: ./frontend
    image: dockerlearn255/frontend:1.0.0
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment

  mongodb:
    build: ./Mongodb
    image: dockerlearn255/mongodb:1.0.0  #docker build -t dockerlearn255/mongodb:1.0.0 .  #it should be run from mongodb directory
    container_name: mongodb    
    # volumes:
    #   - mongodb:/data/db   #this is for data persistence, so that even if container is removed, data will be there in volume and can be reused by new container.

  redis:
    image: redis:7.0
    container_name: redis 
    # volumes:
    #   - redis:/data   #this is for data persistence, so that even if container is removed, data will be there in volume and can be reused by new container.

  mysql:
    build: ./mysql
    image: dockerlearn255/mysql:1.0.0 
    container_name: mysql  
    # volumes:
    #   - mysql:/var/lib/mysql   #this is for data persistence, so that even if container is removed, data will be there in volume and can be reused by new container. 

  payment:
    build: ./payment
    image: dockerlearn255/payment:1.0.0
    container_name: payment 
    depends_on:
      - user
      - cart
      - rabbitmq
    environment:
      CART_HOST: "cart"
      CART_PORT: "8080"
      USER_HOST: "user"
      USER_PORT: "8080"
      AMQP_HOST: "rabbitmq"
      AMQP_USER: "roboshop"
      AMQP_PASSWORD: "roboshop123"

      
  rabbitmq:
    image: rabbitmq:3
    environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: password
    container_name: rabbitmq
    # volumes:
    #   - rabbitmq:/var/lib/rabbitmq   #this is for data persistence, so that even if container is removed, data will be there in volume and can be reused by new container.


networks:
  default:
    driver: bridge
    name: roboshop 
    external: false  


# volumes:
#   mongodb:   # docker volume create mongodb
#   rabbitmq:
#   sql:
#   redis:      